steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/php:$SHORT_SHA', '-f', './docker/Dockerfile', '.' ]
# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: [ "push", "gcr.io/$PROJECT_ID/php:$SHORT_SHA" ]
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - helloworld-php
    - --image
    - gcr.io/$PROJECT_ID/php:$SHORT_SHA
    - --region
    - us-central1
    - --platform
    - managed
    - --allow-unauthenticated
  env:
    - 'PORT=80'
